### ISSUE TITLE
User can turn the car

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create CSS classes for rotating the car to each of the four directions
- [x] Add a keydown event listener for each of the arrows on the keyboard
- [x] Create functions that changes the classes to each direction
- [x] Add event listener for each of the arrow keys linked to the correct direction function (class change)
- [x] Check each direction is correct
- [x] Make transitions so the car doesn't just pop to each direction
