### ISSUE TITLE
User can start car

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/driving-game#4]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Create a data model to keep track of x and y coordinates of the car
- [x] Make car position absolute
- [x] Make function with intervals for increment movement of the car on the page
- [x] Save x and y coordinates on the data object
- [x] Make car stop at the edge of the page
- [x] Add event listener to space button to make car move
