### ISSUE TITLE
User can stop car

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/driving-game#6]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Toggle driving on or off in data object if car is moving
- [x] On spacebar event listener, retrieve driving on or off
- [x] If car is moving, stop car
- [x] If car is stopped, start and move car
- [x] Check all current functionalities work
