### ISSUE TITLE
Issue 5 steer car

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/driving-game#8]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Edit move car function so that it checks the data object direction and if driving is true
- [x] Increase intervals based on the direction of the car x OR y axis
- [x] Save the new x or y axis in the data object
- [x] Check all functionalities work
